server:
#  port: 8080
# 随机端口
  port: ${random.int[2000,8000]}
#debug: true

logging:
  file:
    path: ./logs

################### Mybatis config ###################
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.quan.entity

################### Spring config begin ###################
spring:
  application:
    name: spring-water-application
  ################### Datasource config ###################
  datasource:
    username: root
    password: ENC(h0FuKCIDDxtJDagwvCWZPg==)
    url: jdbc:mysql://127.0.0.1:3306/cas?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&characterEncoding=utf8&useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

  ################### Jackson config ###################
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: Asia/Shanghai

  ################# Redis config #################
  redis:
    host: 120.76.175.67
    port: 6379
    database: 0
    #    password: ENC(rif+QPIsBzSVxyXJWRoCohI5cQpZE+a9)
    timeout: 1000
    jedis:
      pool:
        max-active: 20
        max-idle: 10
        min-idle: 0
        max-wait: -1

  ################# kafka config #################
  kafka:     # 指定kafka 代理地址，可以多个
    bootstrap-servers: 120.76.175.67:9092
    template:    # 指定默认topic id
      default-topic: producer
    listener:   # 指定listener 容器中的线程数，用于提高并发量
      missing-topics-fatal: false
      concurrency: 100
    #=============== consumer =======================
    consumer:
      # 默认消费者组
      group-id: myGroup
      client-id: 200
      # 批量一次最大拉取数据量
      max-poll-records: 80
      # 最早未被消费的offset
      # 当没有初始偏移量或当前偏移量不存在时设置消费的起始点(earliest、latest、none三个值可选择)
      auto-offset-reset: earliest
      # 是否后台自动提交偏移量
      enable-auto-commit: true
      # 后台自动提交消费偏移量(后台定时提交)的间隔时间
      auto-commit-interval: 1000
      bootstrap-servers: 120.76.175.67:9092
      # 指定消息key和消息体的编解码方式
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      properties:
        session:
          timeout:
            ms: 20000
        max:
          poll:
            interval:
              ms: 10000
    #=============== producer =======================
    producer:
      # 批量发送的消息数量
      batch-size: 16384
      # 32MB的批处理缓冲区
      buffer-memory: 33554432
      # 重试次数
      retries: 3
      client-id: 200
      # 指定消息key和消息体的编解码方式
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      # 生产者要求领导者在考虑完成请求之前收到的确认数量
      acks: 1

  ################# RabbitMQ config #################
  rabbitmq:
    host: 120.76.175.67
    port: 5672
    username: guest
    password: ENC(uLi03Ellq+ON+mXDJajfcQ====)
    virtualHost: /
  ################# Spring Data config begin #################
  data:
    ################### MongoDB config ###################
    mongodb:
      host: 120.76.175.67
      port: 27017
      password: ENC(rif+QPIsBzSVxyXJWRoCohI5cQpZE+a9)
      username: admin
      database: admin
      uri: mongodb://${spring.data.mongodb.username}:${spring.data.mongodb.password}@${spring.data.mongodb.host}:${spring.data.mongodb.port}/${spring.data.mongodb.database}?maxpoolsize=10&minpoolsize=1&maxidletimems=600000&maxlifetimems=1800000

    ################### Neo4j config ###################
    neo4j:
      uri: bolt://120.76.175.67:7687
      username: neo4j
      password: ENC(WQ7khH1e17tw3wivLfCqNw==)
  ################# Spring Data config end #################

################### Spring config end ###################
jasypt:
  encryptor:
    password: jasypt
    # 加密算法设置 3.0.0 以后
    algorithm: PBEWithMD5AndDES
    iv-generator-classname: org.jasypt.iv.NoIvGenerator
