rocketmq:
  name-server: 192.168.3.18:9876
  producer:
    group: producer-group
    retry-times-when-send-failed: 2
    retry-times-when-send-async-failed: 0
    send-message-timeout: 300000
    compress-message-body-threshold: 4096
    max-message-size: 4194304