spring:
  data:
    mongodb:
      uri: mongodb+srv://root:root@force-oneself.rshao.mongodb.net/myFirstDatabase?retryWrites=true&w=majority
      auto-index-creation: true


logging:
  level:
    org.springframework.data.mongodb.core: debug
